#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
MCP LLM Service - LLM統合サービス
"""

import json
import time
from http.server import HTTPServer, BaseHTTPRequestHandler
from typing import Dict, Any


class LLMServiceHandler(BaseHTTPRequestHandler):
    """LLMサービスハンドラー"""

    # キャッシュ（簡易実装）
    cache = {}

    def do_GET(self):
        """GETリクエスト処理"""
        if self.path == "/health":
            self._send_response(200, {
                "status": "healthy",
                "service": "llm",
                "cache_size": len(self.cache)
            })
        else:
            self._send_response(404, {"error": "Not Found"})

    def do_POST(self):
        """POSTリクエスト処理"""
        content_length = int(self.headers.get('Content-Length', 0))
        body = self.rfile.read(content_length).decode('utf-8')

        try:
            data = json.loads(body)
        except json.JSONDecodeError:
            self._send_response(400, {"error": "Invalid JSON"})
            return

        if self.path == "/generate":
            self._handle_generate(data)
        elif self.path == "/chat":
            self._handle_chat(data)
        else:
            self._send_response(404, {"error": "Not Found"})

    def _handle_generate(self, data: Dict[str, Any]):
        """コード生成リクエスト処理"""
        prompt = data.get("prompt", "")
        provider = data.get("provider", "ollama")

        # キャッシュチェック
        cache_key = f"{provider}:{prompt[:100]}"
        if cache_key in self.cache:
            print(f"💾 Cache HIT: {cache_key[:50]}...")
            self._send_response(200, {
                "code": self.cache[cache_key],
                "cached": True,
                "provider": provider
            })
            return

        # LLM呼び出し（ここでは簡易実装）
        print(f"🤖 LLM生成: {prompt[:50]}...")
        time.sleep(0.5)  # シミュレーション

        generated_code = f"""# Generated by {provider}
def main():
    print("Hello from LLM Service")

if __name__ == "__main__":
    main()
"""

        # キャッシュに保存
        self.cache[cache_key] = generated_code

        self._send_response(200, {
            "code": generated_code,
            "cached": False,
            "provider": provider,
            "timestamp": time.time()
        })

    def _handle_chat(self, data: Dict[str, Any]):
        """チャットリクエスト処理"""
        message = data.get("message", "")

        print(f"💬 Chat: {message[:50]}...")
        time.sleep(0.3)

        self._send_response(200, {
            "response": f"LLMからの応答: {message}について理解しました。",
            "timestamp": time.time()
        })

    def _send_response(self, status_code: int, data: Dict[str, Any]):
        """レスポンス送信"""
        self.send_response(status_code)
        self.send_header('Content-Type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps(data, ensure_ascii=False).encode('utf-8'))

    def log_message(self, format, *args):
        """ログメッセージ"""
        print(f"[LLM {time.strftime('%H:%M:%S')}] {format % args}")


def run_llm_service(port: int = 8001):
    """LLMサービス起動"""
    server_address = ('', port)
    httpd = HTTPServer(server_address, LLMServiceHandler)

    print("=" * 60)
    print("🤖 MCP LLM Service")
    print("=" * 60)
    print(f"📡 起動: http://localhost:{port}")
    print("\nエンドポイント:")
    print(f"  GET  /health   - ヘルスチェック")
    print(f"  POST /generate - コード生成")
    print(f"  POST /chat     - チャット")
    print("=" * 60 + "\n")

    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\n🛑 LLMサービス停止中...")
        httpd.shutdown()
        print("✅ LLMサービス停止完了")


if __name__ == "__main__":
    run_llm_service()
