app:
  name: NeuroHub
  timezone: "Asia/Tokyo"
  env: dev
  language: "C"
  locale: "C.UTF-8"

paths:
  base: /home/kenny/NeuroHub
  cache_asr: /home/kenny/NeuroHub/data/cache/asr
  cache_tts: /home/kenny/NeuroHub/data/cache/tts
  cache_mpv: /home/kenny/NeuroHub/data/cache/mpv
  database: /home/kenny/NeuroHub/data/neurohub.db

llm:
  default: gemini
  gemini:
    api_url: https://generativelanguage.googleapis.com/v1
    model: gemini-2.5-flash
    temperature:
    max_output_tokens:
    timeout_sec:
  ollama:
    host: http://127.0.0.1:11434
    models:
      - qwen2.5:1.5b-instruct
      - llama2:latest
      - llama2:70b
    selected_model: qwen2.5:1.5b-instruct
    temperature:
    num_ctx:
    num_thread:

asr:
  engine:
  model:
  timeout_sec:

tts:
  engine:
  model: /home/kenny/NeuroHub/models/piper/ja-kokoro-high.onnx
  out_wav: /home/kenny/NeuroHub/data/cache/tts/out.wav
  speed:

mpv:
  audio_device:
  default_volume:
  ipc_dir: /home/kenny/NeuroHub/data/cache/mpv
  common_opts:

logging:
  level: INFO
  dir: /home/kenny/NeuroHub/logs

system:
  created_at: "2025-10-26T02:44:28+09:00"
  machine_id: "4bcb0392bd274680ad9f76e83c280121"
  hostname: "kenty.localdomain"
  user: "kenny"
  os: "Ubuntu 24.04.1 LTS"
  kernel: "6.6.87.2-microsoft-standard-WSL2"
  arch: "x86_64"
  cpu_model: "13th Gen Intel(R) Core(TM) i7-13620H"
  cpu_cores: 16
  memory_mb: 7792
  ipv4: [10.255.255.254,172.30.227.131]
  project_root: "/home/kenny/NeuroHub"
  locale:
    LANG: "C.UTF-8"
    LC_ALL: ""
    LANGUAGE: ""
    system_locale_line: "LANG=C.UTF-8"
  keyboard:
    vc_keymap: "(unset)"
    x11_layout: "us"
    x11_model: "pc105"
    x11_variant: ""
    x11_options: ""
  desktop:
    current_desktop: ""
    session: ""
