app:
  name: NeuroHub
  timezone: "Asia/Tokyo"
  env: dev
  language: "en-GB"
  locale: "en_GB.UTF-8"

paths:
  base: /home/kennypi/work/NeuroHub
  cache_asr: /home/kennypi/work/NeuroHub/data/cache/asr
  cache_tts: /home/kennypi/work/NeuroHub/data/cache/tts
  cache_mpv: /home/kennypi/work/NeuroHub/data/cache/mpv
  database: /home/kennypi/work/NeuroHub/data/neurohub.db

llm:
  default: gemini
  gemini:
    api_url: https://generativelanguage.googleapis.com/v1
    model: gemini-2.5-flash
    temperature:
    max_output_tokens:
    timeout_sec:
  ollama:
    host: http://127.0.0.1:11434
    models:
      - mxbai-embed-large:latest
      - all-minilm:latest
      - nomic-embed-text:latest
      - moondream:latest
      - tinyllama:1.1b
      - qwen2.5:3b-instruct
      - qwen2.5:0.5b-instruct
      - qwen2.5:1.5b-instruct
    selected_model: mxbai-embed-large:latest
    temperature:
    num_ctx:
    num_thread:

asr:
  engine:
  model:
  timeout_sec:

tts:
  engine:
  model: /home/kennypi/work/NeuroHub/models/piper/ja-kokoro-high.onnx
  out_wav: /home/kennypi/work/NeuroHub/data/cache/tts/out.wav
  speed:

mpv:
  audio_device:
  default_volume:
  ipc_dir: /home/kennypi/work/NeuroHub/data/cache/mpv
  common_opts:

logging:
  level: INFO
  dir: /home/kennypi/work/NeuroHub/logs

system:
  created_at: "2025-10-28T12:37:09+09:00"
  machine_id: "2d7493683df14502b343a8a4617df98d"
  hostname: "k-pi"
  user: "kennypi"
  os: "Debian GNU/Linux 12 (bookworm)"
  kernel: "6.12.47+rpt-rpi-v8"
  arch: "aarch64"
  cpu_model: ""
  cpu_cores: 4
  memory_mb: 950
  ipv4: [192.168.3.30,100.73.218.99]
  project_root: "/home/kennypi/work/NeuroHub"
  locale:
    LANG: "en_GB.UTF-8"
    LC_ALL: ""
    LANGUAGE: ""
    system_locale_line: "LANG=en_GB.UTF-8"
  keyboard:
    vc_keymap: "(unset)"
    x11_layout: "jp"
    x11_model: "pc105"
    x11_variant: ""
    x11_options: ""
  desktop:
    current_desktop: ""
    session: ""
